version: '3'

services:
  books:
    build: ./Books
    ports:
      - "8080:8080"
    networks:
      - app-network
  reviews:
    build: ./reviews
    ports:
      - "8081:8081"
    networks:
      - app-network
  details:
    build: ./details
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
