name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Books image
        run: docker build -t username/books:latest ./Books

      - name: Build and push Reviews image
        run: docker build -t username/reviews:latest ./reviews

      - name: Build and push Details image
        run: docker build -t username/details:latest ./details

      - name: Push to Docker Hub
        run: docker push username/books:latest && docker push username/reviews:latest && docker push username/details:latest
